production:
  adapter: postgresql
  database: danbooru2
  pool: 5
  timeout: 5000
  url: postgresql://__POSTGRES_USERNAME__:__POSTGRES_PASSWORD__@__POSTGRES_HOSTNAME__/__POSTGRES_DATABASE__

# read only databases, just point to local copies if you have no need
ro_production:
  adapter: postgresql
  database: danbooru2
  url: postgresql://__POSTGRES_USERNAME__:__POSTGRES_PASSWORD__@__POSTGRES_HOSTNAME__/__POSTGRES_DATABASE__

archive_production:
  adapter: postgresql
  database: archive_development
  url: postgresql://__POSTGRES_USERNAME__:__POSTGRES_PASSWORD__@__POSTGRES_HOSTNAME__/__POSTGRES_DATABASE__
